# -*- coding: utf-8 -*-
"""Automate Dicky Saragih

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1acRWrbH9a9JPwT_oqs1VnENlb9KBO8Vi
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import os

# === 1. Muat Dataset ===
input_path = "WineQT.csv"
output_path = "WineQT_processed.csv"

# Membaca dataset
df = pd.read_csv(input_path)
print(f"Dataset dimuat: {df.shape[0]} baris, {df.shape[1]} kolom")

# === 2. Preprocessing ===
df = df.drop_duplicates()
df = df.dropna()

X = df.drop("quality", axis=1)
y = df["quality"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

df_processed = pd.DataFrame(X_scaled, columns=X.columns)
df_processed["quality"] = y.values

# === 3. Simpan Dataset ===
# Buat direktori jika belum ada
output_dir = os.path.dirname(output_path)
if output_dir and not os.path.exists(output_dir):
    os.makedirs(output_dir)

df_processed.to_csv(output_path, index=False)
print(f"Dataset hasil preprocessing disimpan di: {output_path}")

