name: Preprocessing Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn numpy

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_dicky_saragih.py

    - name: Upload preprocessed dataset
      uses: actions/upload-artifact@v3
      with:
        name: preprocessed-data
        path: preprocessing/WineQT_processed.csv
